language: cpp
dist: trusty
sudo: require
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - clang-7
      - cmake
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
  - sudo ln -s /usr/bin/clang-7 /usr/local/bin/clang
  - cmake ../mp2-lab1-set
  - make -j
  - cd ./bin/
  - ./test_set --gtest_list_tests
notifications:
  email: false
